package com.gitfast.app.data.sync

import com.gitfast.app.data.local.entity.CharacterProfileEntity
import com.gitfast.app.data.local.entity.GpsPointEntity
import com.gitfast.app.data.local.entity.LapEntity
import com.gitfast.app.data.local.entity.RouteTagEntity
import com.gitfast.app.data.local.entity.UnlockedAchievementEntity
import com.gitfast.app.data.local.entity.WorkoutEntity
import com.gitfast.app.data.local.entity.WorkoutPhaseEntity
import com.gitfast.app.data.local.entity.XpTransactionEntity
import com.gitfast.app.data.model.ActivityType
import com.gitfast.app.data.model.EnergyLevel
import com.gitfast.app.data.model.PhaseType
import com.gitfast.app.data.model.WeatherCondition
import com.gitfast.app.data.model.WeatherTemp
import com.gitfast.app.data.model.WorkoutStatus

// --- WorkoutEntity ---

fun WorkoutEntity.toFirestoreMap(): Map<String, Any?> = mapOf(
    "id" to id,
    "startTime" to startTime,
    "endTime" to endTime,
    "totalSteps" to totalSteps,
    "distanceMeters" to distanceMeters,
    "status" to status.name,
    "activityType" to activityType.name,
    "dogName" to dogName,
    "notes" to notes,
    "weatherCondition" to weatherCondition?.name,
    "weatherTemp" to weatherTemp?.name,
    "energyLevel" to energyLevel?.name,
    "routeTag" to routeTag,
)

fun Map<String, Any?>.toWorkoutEntity(): WorkoutEntity = WorkoutEntity(
    id = this["id"] as String,
    startTime = (this["startTime"] as Number).toLong(),
    endTime = (this["endTime"] as? Number)?.toLong(),
    totalSteps = (this["totalSteps"] as Number).toInt(),
    distanceMeters = (this["distanceMeters"] as Number).toDouble(),
    status = WorkoutStatus.valueOf(this["status"] as String),
    activityType = ActivityType.valueOf(this["activityType"] as String),
    dogName = this["dogName"] as? String,
    notes = this["notes"] as? String,
    weatherCondition = (this["weatherCondition"] as? String)?.let { WeatherCondition.valueOf(it) },
    weatherTemp = (this["weatherTemp"] as? String)?.let { WeatherTemp.valueOf(it) },
    energyLevel = (this["energyLevel"] as? String)?.let { EnergyLevel.valueOf(it) },
    routeTag = this["routeTag"] as? String,
)

// --- WorkoutPhaseEntity ---

fun WorkoutPhaseEntity.toFirestoreMap(): Map<String, Any?> = mapOf(
    "id" to id,
    "workoutId" to workoutId,
    "type" to type.name,
    "startTime" to startTime,
    "endTime" to endTime,
    "distanceMeters" to distanceMeters,
    "steps" to steps,
)

fun Map<String, Any?>.toWorkoutPhaseEntity(): WorkoutPhaseEntity = WorkoutPhaseEntity(
    id = this["id"] as String,
    workoutId = this["workoutId"] as String,
    type = PhaseType.valueOf(this["type"] as String),
    startTime = (this["startTime"] as Number).toLong(),
    endTime = (this["endTime"] as? Number)?.toLong(),
    distanceMeters = (this["distanceMeters"] as Number).toDouble(),
    steps = (this["steps"] as Number).toInt(),
)

// --- LapEntity ---

fun LapEntity.toFirestoreMap(): Map<String, Any?> = mapOf(
    "id" to id,
    "phaseId" to phaseId,
    "lapNumber" to lapNumber,
    "startTime" to startTime,
    "endTime" to endTime,
    "distanceMeters" to distanceMeters,
    "steps" to steps,
    "splitLatitude" to splitLatitude,
    "splitLongitude" to splitLongitude,
)

fun Map<String, Any?>.toLapEntity(): LapEntity = LapEntity(
    id = this["id"] as String,
    phaseId = this["phaseId"] as String,
    lapNumber = (this["lapNumber"] as Number).toInt(),
    startTime = (this["startTime"] as Number).toLong(),
    endTime = (this["endTime"] as? Number)?.toLong(),
    distanceMeters = (this["distanceMeters"] as Number).toDouble(),
    steps = (this["steps"] as Number).toInt(),
    splitLatitude = (this["splitLatitude"] as? Number)?.toDouble(),
    splitLongitude = (this["splitLongitude"] as? Number)?.toDouble(),
)

// --- GpsPointEntity ---

fun GpsPointEntity.toFirestoreMap(): Map<String, Any?> = mapOf(
    "workoutId" to workoutId,
    "latitude" to latitude,
    "longitude" to longitude,
    "timestamp" to timestamp,
    "accuracy" to accuracy,
    "sortIndex" to sortIndex,
    "speed" to speed,
)

fun Map<String, Any?>.toGpsPointEntity(): GpsPointEntity = GpsPointEntity(
    id = 0, // auto-generated by Room
    workoutId = this["workoutId"] as String,
    latitude = (this["latitude"] as Number).toDouble(),
    longitude = (this["longitude"] as Number).toDouble(),
    timestamp = (this["timestamp"] as Number).toLong(),
    accuracy = (this["accuracy"] as Number).toFloat(),
    sortIndex = (this["sortIndex"] as Number).toInt(),
    speed = (this["speed"] as? Number)?.toFloat(),
)

// --- RouteTagEntity ---

fun RouteTagEntity.toFirestoreMap(): Map<String, Any?> = mapOf(
    "name" to name,
    "createdAt" to createdAt,
    "lastUsed" to lastUsed,
)

fun Map<String, Any?>.toRouteTagEntity(): RouteTagEntity = RouteTagEntity(
    name = this["name"] as String,
    createdAt = (this["createdAt"] as Number).toLong(),
    lastUsed = (this["lastUsed"] as Number).toLong(),
)

// --- CharacterProfileEntity ---

fun CharacterProfileEntity.toFirestoreMap(): Map<String, Any?> = mapOf(
    "id" to id,
    "totalXp" to totalXp,
    "level" to level,
    "createdAt" to createdAt,
    "speedStat" to speedStat,
    "enduranceStat" to enduranceStat,
    "consistencyStat" to consistencyStat,
)

fun Map<String, Any?>.toCharacterProfileEntity(): CharacterProfileEntity = CharacterProfileEntity(
    id = (this["id"] as Number).toInt(),
    totalXp = (this["totalXp"] as Number).toInt(),
    level = (this["level"] as Number).toInt(),
    createdAt = (this["createdAt"] as Number).toLong(),
    speedStat = (this["speedStat"] as Number).toInt(),
    enduranceStat = (this["enduranceStat"] as Number).toInt(),
    consistencyStat = (this["consistencyStat"] as Number).toInt(),
)

// --- XpTransactionEntity ---

fun XpTransactionEntity.toFirestoreMap(): Map<String, Any?> = mapOf(
    "id" to id,
    "workoutId" to workoutId,
    "xpAmount" to xpAmount,
    "reason" to reason,
    "timestamp" to timestamp,
    "profileId" to profileId,
)

fun Map<String, Any?>.toXpTransactionEntity(): XpTransactionEntity = XpTransactionEntity(
    id = this["id"] as String,
    workoutId = this["workoutId"] as String,
    xpAmount = (this["xpAmount"] as Number).toInt(),
    reason = this["reason"] as String,
    timestamp = (this["timestamp"] as Number).toLong(),
    profileId = (this["profileId"] as Number).toInt(),
)

// --- UnlockedAchievementEntity ---

fun UnlockedAchievementEntity.toFirestoreMap(): Map<String, Any?> = mapOf(
    "achievementId" to achievementId,
    "unlockedAt" to unlockedAt,
    "xpAwarded" to xpAwarded,
    "profileId" to profileId,
)

fun Map<String, Any?>.toUnlockedAchievementEntity(): UnlockedAchievementEntity = UnlockedAchievementEntity(
    achievementId = this["achievementId"] as String,
    unlockedAt = (this["unlockedAt"] as Number).toLong(),
    xpAwarded = (this["xpAwarded"] as Number).toInt(),
    profileId = (this["profileId"] as Number).toInt(),
)

// --- Settings (to/from Map for user doc) ---

fun settingsToFirestoreMap(
    autoPauseEnabled: Boolean,
    distanceUnit: String,
    keepScreenOn: Boolean,
    autoLapEnabled: Boolean,
    autoLapAnchorRadiusMeters: Int,
    homeArrivalEnabled: Boolean,
    homeLatitude: Double?,
    homeLongitude: Double?,
    homeArrivalRadiusMeters: Int,
): Map<String, Any?> = mapOf(
    "autoPauseEnabled" to autoPauseEnabled,
    "distanceUnit" to distanceUnit,
    "keepScreenOn" to keepScreenOn,
    "autoLapEnabled" to autoLapEnabled,
    "autoLapAnchorRadiusMeters" to autoLapAnchorRadiusMeters,
    "homeArrivalEnabled" to homeArrivalEnabled,
    "homeLatitude" to homeLatitude,
    "homeLongitude" to homeLongitude,
    "homeArrivalRadiusMeters" to homeArrivalRadiusMeters,
)
